### ISSUE TITLE
Plan for Jakarta EE 11

### ISSUE THREAD

**Issue by KyleAure** [jakartaee/jsonb-api#352]
I just wanted to verify that JSON Binding is not doing a new release for Jakarta EE 11.
I haven't seen anything on github, the eclipse site, or the mailing list to indicate that a new release is happening for EE 11 but wanted to verify.

@Verdent can you confirm this?

**Comment by Verdent** [comment]
@KyleAure I am not currently participating any release preparation, but I have seen some discussion about new features and spec clarifications with @mkarg. Markus, do you have any updates?

**Comment by mkarg** [comment]
I am not involved in JSON-B.

**Comment by Verdent** [comment]
@KyleAure In that case, I think it is safe to say, there is nothing planned.

**Comment by KyleAure** [comment]
@Verdent @mkarg are you looking for new/more committers?  I'd like to offer some support for this spec. If you have any issues you'd like me to work on for EE 12 let me know.

**Comment by mkarg** [comment]
More hands are always a good thing, so feel free to work on any open issue you find. :-)
