### ISSUE TITLE
Multiple objects in stream

### ISSUE THREAD

**Issue by mnlipp** [jakartaee/jsonb-api#364]
Last week , I evaluated the possibility to replace Jackson with json-b in an application. It turns out to be impossible.

The application opens a stream and sends Json notifications on it to notify about application level events. This is [no problem with Jackson](https://github.com/mnlipp/jgrapes-webconsole/blob/a235162904e5dc3fce2baee508992dcafec67d24/org.jgrapes.webconsole.base/test/org/jgrapes/webcon/base/test/JsonRpcTests.java#L45), as its approach is to parse whatever it is supposed to (an object in this case) and then leave the input alone. Json-b, however, considers anything following the last excpected token to be garbage.

IMHO this behavior should be made configurable in a future version.

**Comment by rmannibucau** [comment]
Hi @mnlipp ,

this is invalid JSON (and invalid JSON-RPC request) so if you want to handle it you likely need a custom inputstream you integrate with a jsonparser to rewind when you detect a second object and restart the parsing.
then jsonparser can be integrated with jsonb.

...but ultimately this is not a valid use case for anything JSON*

**Comment by mnlipp** [comment]
@rmannibucau Thanks for your answer. But could you provide me with a link to some specification that confirms that this is invalid? The RFC defines Jsdon as a [text](https://datatracker.ietf.org/doc/html/rfc8259#section-2). Nowhere does it state that only one such text may be transfered over a connection/stream.

**Comment by rmannibucau** [comment]
@mnlipp the link you point explains it, it is *not* a text but `A JSON text is a sequence of tokens.  The set of tokens includes six structural characters, strings, numbers, and three literal names.` and JSON-P/JSON-B comply to that. Parts after the link you provide detail the grammar, concatenated objects are not in this grammar.

**Comment by mnlipp** [comment]
@rmannibucau  Sorry, but I don't understand your point. Nowhere in my text with "catenated" objects is an invalid token.  And I don't see where the RFC specifies that a parser should attempt to get more tokens beyond those that make up a `JSON-text = ws value ws` when it is asked to parse a `JSON-text`.

**Comment by rmannibucau** [comment]
@mnlipp a spec must be read as "what is not written is not supported", where is it written it works? nowhere. The parser uses `ws value ws` but when you check what value is, it is literally what I quoted before which makes concatenated json value out of scope.

**Comment by mnlipp** [comment]
> "what is not written is not supported"

I tend to disagree. A spec should be read as "as long as you comply to what's specified, things should work".

However, it's not that important. The (long term) move to Json-B was considered because in general having more than one supplier (i.e. implementation) tends to be a plus. But I doubt that Jackson (and its interpretation of the standard) will go away (or loose support) any time soon.

**Comment by rmannibucau** [comment]
> I tend to disagree. A spec should be read as "as long as you comply to what's specified, things should work".

Well "as long as you comply to what's specified, things should work" is true and literally means "while you use what is explicitly written" and here the grammar is explicit and forbids your case.

You also seems to use JSON-RPC where it would be pretty unusable: `{"jsonrpc":"2.0","method":"...","params":{"foo":{}{},"bar":[][],"dummy":"abc""efg"}}`

These are all cases which are expected to be erroneous.

Do you have a reason to try to parse "{}{}" as a multistream object?
The ecosystem standard is JSONNL and NL split is delegated to the caller for JSON-P/JSON-B anyway so seems your use case is more a bug until you can provide more details.

Last thing is that jackson explicitly mentions it is a non compliant behavior (https://github.com/FasterXML/jackson-core/issues/1323).

Note that the link referenced in this PR just use the link you provided to show it should be supported and it explicit visually it is forbidden: https://www.json.org/json-en.html

**Comment by mnlipp** [comment]
Jackson has it as a ["turn-on/turn-off feature"](https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/DeserializationFeature.html#FAIL_ON_TRAILING_TOKENS) which is what I initially suggested for Json-B.

> Do you have a reason to try to parse "{}{}" as a multistream object?

It is what I mentioned at the beginning of this discussion: "The application opens a stream and sends Json notifications [read as `JSON-text` messages] on it to notify about application level events."

This is similar to sending several YAML-documents over one connection using the "---" separator or several HTTP requests over one connection (which became possible in HTTP/1.1, using "Content-Length" instead of a separator). Json doesn't need either mechanism because "value" in `JSON-text = ws value ws` is either a primitive or "balanced" by outer "[]" or "{}". (BTW your example `{"jsonrpc":"2.0","method":"...","params":{"foo":{}{},"bar":[][],"dummy":"abc""efg"}}` violates the grammer; top-level "{...}{...}") does not. It's just `stream-content = JSON-text JSON-text`.)

Opening a new connection for every notification is out of the question for performance reasons. Using some additional "wrapper" such as "---Begin Json---" and "---End Json---" to split the stream in separate `JSON-texts` introduces unnecessary overhead, because nothing else but Json notifications come over the connection. (And besides, it would require a pass through a Json parser, else "---End Json---" as text value within the Json might erroneously be detected as end-of-JSON-text). A control character which is illegal in Json such as page break (Ctrl-L) could be used as a simple separator, but this would still require processing the text twice without any real necessity.

**Comment by rmannibucau** [comment]
> "The application opens a stream and sends Json notifications [read as JSON-text messages] on it to notify about application level events."

there are two standards in the industry for that:

1. sse payload
2. jsonnl

and both dont need any hack at json parser level

so if something to integrate with it should be standard and not application specific so I don't think it would be wise to support this hack.

> Opening a new connection for every notification is out of the question for performance reasons. 

Ack but no need.

> Using some additional "wrapper" such as "---Begin Json---" and "---End Json---" to split the stream in separate JSON-texts introduces unnecessary overhead, because nothing else but Json notifications come over the connection.

Just `\n`, overhead is negligible and you have all you need to implement it without having to make a JSON spec supporting something which is not JSON - it is quite common to use JSON-B with JSONNL .


> Json doesn't need either mechanism because "value" in JSON-text = ws value ws is either a primitive or "balanced" by outer "[]" or "{}". 

Please stop saying it is valid, it is *invalid* for json spec and *invalid* from jackson standpoint too. Here again the link you provided explicit states it: https://datatracker.ietf.org/doc/html/rfc8259#section-3

**Comment by mnlipp** [comment]
> Here again the link you provided explicit states it: https://datatracker.ietf.org/doc/html/rfc8259#section-3

Sorry, don't follow. That's the definition of a Json value. Doesn't specify that you can only have only one `JSON-text` in a stream.

But it's okay. Json-B won't support it and I'll stick to Jackson. Everything is fine.
